language: scala

scala:
   - 2.13.3
   
jdk:
  - openjdk8

# https://github.com/olafurpg/sbt-ci-release#travisyml
before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - env: TEST="all"
      script: 
        - sbt ++$TRAVIS_SCALA_VERSION test
    - stage: release
      script: sbt ci-release
    
notifications:
  email:
    - sakib@sake.ba

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt